// One-line run summaries, generated out of band.
//
// The agent never writes these. Asking it would put the request into its own
// transcript, which is the one place it must not go: a real turn costs a full
// inference, grows the context, and can tip a nearly-full context into
// auto-compaction. So the summary is produced by a separate small model, from the
// last exchange only, and cached per run by whoever asked for it.
//
// Trade, stated plainly: this server reads that exchange — the user's last
// message and the final reply. Same class of decision as voice (an excerpt rather
// than a whole transcript), and it is the user's own box. The summary is returned
// over TLS and stored by the client, never folded into session `meta`, which is
// deliberately sent in the clear so the hub can track names and directories.
//
// Precedent for the shape: conversation titles in LibreChat and ChatGPT-Next-Web
// are generated by a dedicated "task model", deliberately decoupled from the main
// message so a failed turn still gets titled.

export const SUMMARY_MAX_CHARS = 100;

const SYSTEM = `You write one-line summaries of a coding agent's completed work, for a sidebar list.

Rules:
- One line, at most 80 characters.
- Past tense, what was accomplished: "Fixed the spawn scope check", "Added voice dictation".
- Name the concrete thing (feature, file, subsystem). No filler like "Successfully".
- Never address the reader, never offer next steps, never use markdown, quotes or emoji.
- If the turn was trivial, exploratory or failed, say that plainly: "Investigated the timeout", "No changes made".
Output only that line, nothing else.`;

/** Trim the habits models fall into: quotes, markdown, a trailing period, length. */
export function cleanSummary(text) {
  const first = String(text ?? "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)[0] ?? "";
  const stripped = first
    .replace(/^[`*"'\-–—\s]+/, "")
    .replace(/[`*"'.\s]+$/, "")
    .replace(/\*\*/g, "")
    .trim();
  if (!stripped) return "";
  return stripped.length > SUMMARY_MAX_CHARS ? `${stripped.slice(0, SUMMARY_MAX_CHARS - 1).trimEnd()}…` : stripped;
}

export function createSummaryService({ env = process.env, fetchImpl = fetch } = {}) {
  const apiKey = env.GROQ_API_KEY ?? env.OPENAI_API_KEY;
  if (!apiKey || env.PINET_SUMMARY === "off") {
    return { enabled: false, summarise: async () => ({ summary: "" }) };
  }
  const baseUrl = env.PINET_SUMMARY_URL ?? "https://api.groq.com/openai/v1";
  const model = env.PINET_SUMMARY_MODEL ?? "qwen/qwen3.8-27b";

  return {
    enabled: true,
    /**
     * One exchange in, one line out. Truncated defensively: the caller is the
     * owner's own client, but nothing here should be able to spend unbounded
     * tokens on a pasted transcript.
     */
    async summarise({ user = "", assistant = "" } = {}) {
      const exchange = `USER: ${String(user).slice(0, 4_000)}\n\nASSISTANT: ${String(assistant).slice(0, 6_000)}`;
      const res = await fetchImpl(`${baseUrl}/chat/completions`, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          model,
          messages: [
            { role: "system", content: SYSTEM },
            { role: "user", content: exchange },
          ],
          temperature: 0.2,
          max_tokens: 64,
        }),
        signal: AbortSignal.timeout(20_000),
      });
      if (!res.ok) {
        const error = new Error(`summary ${res.status}`);
        error.status = res.status;
        throw error;
      }
      const json = await res.json().catch(() => null);
      return { summary: cleanSummary(json?.choices?.[0]?.message?.content) };
    },
  };
}
