// One-line run summaries, generated out of band.
//
// The agent never writes these. Asking it would put the request into its own
// transcript, which is the one place it must not go: a real turn costs a full
// inference, grows the context, and can tip a nearly-full context into
// auto-compaction. So the summary is produced by a separate small model, from the
// last exchange only, and cached per run by whoever asked for it.
//
// Trade, stated plainly: this server reads that exchange — the user's last
// message and the final reply. Same class of decision as voice (an excerpt rather
// than a whole transcript), and it is the user's own box. The summary is returned
// over TLS and stored by the client, never folded into session `meta`, which is
// deliberately sent in the clear so the hub can track names and directories.
//
// Precedent for the shape: conversation titles in LibreChat and ChatGPT-Next-Web
// are generated by a dedicated "task model", deliberately decoupled from the main
// message so a failed turn still gets titled.

import { appendFileSync, mkdirSync, renameSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname } from "node:path";

export const SUMMARY_MAX_LINES = 6;
export const SUMMARY_MAX_LINE_CHARS = 90;
/** Kept for callers that only want the first line's budget. */
export const SUMMARY_MAX_CHARS = SUMMARY_MAX_LINE_CHARS;

const SYSTEM = `You write the short status line that appears beside a coding agent's session, so that someone glancing at a list knows what happened and whether they are needed.

Write one to three lines. Each line is at most 90 characters.

Start the first line with a label when one fits:
  Done — you completed the work
  Answered — you answered a question rather than changing code
  Waiting — you ended by asking the user something, or need a decision, approval or feedback
  Blocked — you could not proceed
  No changes — you investigated or explained, and changed nothing
More than one may apply. Put each label on its own line, followed by the text that
belongs to it on the next line, most urgent first:
  Waiting
  needs a decision on the provider
  Blocked
  the sandbox image is missing

After the label, name the concrete thing: the feature, file or subsystem. A second line may give the current state — what is true now, what is left. A third line only if genuinely needed.

Rules:
- Put whatever the user must act on first. If you are waiting on them, that is the headline, not a footnote.
- Past tense for what happened, present tense for the state.
- No markdown, no quotes, no emoji, no preamble, no "I".
- Never invent progress. If nothing changed, say "No changes".
- If the turn answered a question, answer it in the line: "Answered — the timeout comes from the proxy, not the client".
Output only those lines.`;

/**
 * Trim the habits models fall into: markdown bullets, bold, quotes, a stray
 * preamble line, and lines that run long. Keeps at most three lines, because that
 * is what the display has room for.
 */
export function cleanSummary(text) {
  const lines = String(text ?? "")
    .split("\n")
    .map((line) =>
      line
        .replace(/^\s*(?:[>*•-]|\d+[.)])\s+/, "")
        .replace(/[`*]/g, "")
        // Edge quotes only: an apostrophe inside a word is left alone.
        .replace(/^["'\u201c\u201d]+|["'\u201c\u201d]+$/g, "")
        .replace(/\s+$/, "")
        .trim(),
    )
    .filter(Boolean)
    .slice(0, SUMMARY_MAX_LINES);
  return lines
    .map((line) => (line.length > SUMMARY_MAX_LINE_CHARS ? `${line.slice(0, SUMMARY_MAX_LINE_CHARS - 1).trimEnd()}…` : line))
    .join("\n")
    .replace(/[.]$/, "");
}

/**
 * Append-only JSONL of what the summary model was asked and what it said, so a bad
 * line can be explained after the fact instead of guessed at.
 *
 * The exchange itself is *not* recorded by default — only its shape and a hash, so
 * calls can be correlated without writing session content to a file on this server.
 * `PINET_SUMMARY_LOG_INPUT=1` includes it, for when that is what you are debugging.
 * Rotates once past the cap, keeping one previous file. Logging never throws into a
 * summary: a failure to write is a failure to observe, not a failure to work.
 */
export function createSummaryLog({ path, maxBytes = 5 * 1024 * 1024 } = {}) {
  if (!path) return undefined;
  try {
    mkdirSync(dirname(path), { recursive: true });
  } catch {
    /* the directory already exists, or cannot be made: the writer below copes */
  }
  return (record) => {
    try {
      try {
        if (statSync(path).size > maxBytes) renameSync(path, `${path}.1`);
      } catch {
        /* no file yet */
      }
      appendFileSync(path, `${JSON.stringify({ at: new Date().toISOString(), ...record })}\n`);
    } catch {
      /* never let observability break the thing being observed */
    }
  };
}

const shortHash = (text) => createHash("sha256").update(text).digest("hex").slice(0, 12);

export function createSummaryService({ env = process.env, fetchImpl = fetch, log } = {}) {
  const apiKey = env.GROQ_API_KEY ?? env.OPENAI_API_KEY;
  if (!apiKey || env.PINET_SUMMARY === "off") {
    return { enabled: false, summarise: async () => ({ summary: "" }) };
  }
  const baseUrl = env.PINET_SUMMARY_URL ?? "https://api.groq.com/openai/v1";
  const model = env.PINET_SUMMARY_MODEL ?? "qwen/qwen3.8-27b";
  const record = log ?? createSummaryLog({ path: env.PINET_SUMMARY_LOG === "off" ? undefined : (env.PINET_SUMMARY_LOG ?? "/var/lib/pinet/summaries.jsonl") });
  const withInput = env.PINET_SUMMARY_LOG_INPUT === "1";

  return {
    enabled: true,
    /**
     * One exchange in, one line out. Truncated defensively: the caller is the
     * owner's own client, but nothing here should be able to spend unbounded
     * tokens on a pasted transcript.
     */
    async summarise({ user = "", assistant = "" } = {}) {
      const started = Date.now();
      const exchange = `USER: ${String(user).slice(0, 4_000)}\n\nASSISTANT: ${String(assistant).slice(0, 6_000)}`;
      const shape = {
        userChars: String(user ?? "").length,
        assistantChars: String(assistant ?? "").length,
        hash: shortHash(exchange),
        ...(withInput ? { input: exchange } : {}),
      };
      let res;
      try {
        res = await fetchImpl(`${baseUrl}/chat/completions`, {
        method: "POST",
        headers: { "content-type": "application/json", authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          model,
          messages: [
            { role: "system", content: SYSTEM },
            { role: "user", content: exchange },
          ],
          temperature: 0.2,
          max_tokens: 500,
        }),
          signal: AbortSignal.timeout(20_000),
        });
      } catch (error) {
        record?.({ kind: "summary", model, ms: Date.now() - started, error: String(error?.name ?? error), ...shape });
        throw error;
      }
      if (!res.ok) {
        record?.({ kind: "summary", model, status: res.status, ms: Date.now() - started, error: "http", ...shape });
        const error = new Error(`summary ${res.status}`);
        error.status = res.status;
        throw error;
      }
      const json = await res.json().catch(() => null);
      const raw = String(json?.choices?.[0]?.message?.content ?? "");
      const summary = cleanSummary(raw);
      // `raw` is kept as well: the difference between what the model said and what
      // survived cleaning is exactly what you want to see when a line reads wrong.
      record?.({
        kind: "summary",
        model,
        status: res.status,
        ms: Date.now() - started,
        raw,
        summary,
        lines: summary ? summary.split("\n").length : 0,
        ...shape,
      });
      return { summary };
    },
  };
}
